### PR TITLE
Allow Decoder::next_image() to be called multiple times to allow paging through a multi-page TIFF

### LINKED ISSUE #34: Missing docs/examples for decoder.next_image()
The function `decoder.next_image()` is under-documented.

First off, it is not clear how this function relates to `read_image()` and what the difference between them is.

Second, the naive approach to using it does not compile:

```rust
fn decode(data: &[u8]) {
    let cursor = Cursor::new(data);
    if let Ok(mut decoder) = Decoder::new(cursor) {
        while decoder.more_images() {
            decoder.next_image();
        }
    }
}
```
This fails with the following error:
```
error[E0382]: borrow of moved value: `decoder`
  --> src/bin/tiff-afl-multi.rs:11:19
   |
11 |             while decoder.more_images() {
   |                   ^^^^^^^ value borrowed here after move
12 |                 decoder.next_image();
   |                 ------- value moved here, in previous iteration of loop
   |
   = note: move occurs because `decoder` has type `tiff::decoder::Decoder<std::io::Cursor<&[u8]>>`, which does not implement the `Copy` trait
```
A code example that uses it correctly would be appreciated.

### PR DESCRIPTION
**Pull request by jimrybarski**
Due to some ownership issues, it does not seem possible to iterate through a multi-page TIFF, since `next_image` can only be called once. I just fiddled with the borrows a bit. This should fix #34.

### CODE REVIEW

**Comment by jimrybarski** [comment]
There is one failing test but it should be fixed by #32

**Comment by birktj** [comment]
I want to merge this as it should make the library more usable. @HeroicKatora do you have any objections?

After this and #41 is merged I think we should release a new version of the library,

**Comment by HeroicKatora** [comment]
Seems fine. If you're ready for releasing `0.3` feel free to ping me.
